#!/bin/bash

if [[ "$SOURCE_BRANCH" = "noetic/develop" ]]; then
    # add -t flag to checkout.bash and update image dependencies
    sed -i "s|/checkout.bash|/checkout.bash -d|g; s|usdotfhwastol|usdotfhwastoldev|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:noetic-develop|g" \
        carma-messenger-core/Dockerfile
elif [[ "$SOURCE_BRANCH" =~ ^release/.*$ ]]; then
    # swap checkout branch in checkout.bash to release branch
    RELEASE_NAME=$(echo $SOURCE_BRANCH | cut -d "/" -f 2)
    sed -i "s|usdotfhwastol/|usdotfhwastolcandidate/|g; s|usdotfhwastoldev/|usdotfhwastolcandidate/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:CARMA[a-zA-Z]*_[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:carma-[a-zA-Z]*-[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:develop|:$RELEASE_NAME|g" \
        Dockerfile
    sed -i "s|CARMA[a-zA-Z]*_[0-9]*\.[0-9]*\.[0-9]*|$SOURCE_BRANCH|g; s|carma-[a-zA-Z]*-[0-9]*\.[0-9]*\.[0-9]*|$SOURCE_BRANCH|g" \
        docker/checkout.bash
fi
