#  Copyright (C) 2018-2023 LEIDOS.
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# Docker Compose Spec Version
services:
  messenger_ros2:
    image: ${DOCKER_ORG}/carma-messenger-core:${DOCKER_TAG}
    network_mode: host
    container_name: messenger_ros2
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/routes:/opt/carma/routes
      - /opt/carma/vehicle:/opt/carma/vehicle
    command: bash -c 'source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/carma-messenger-docker.launch.py'

  v2x_ros_driver:
    image: ${DOCKER_ORG}/v2x-ros-driver:${DOCKER_TAG}
    container_name: v2x-ros-driver
    network_mode: host
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
    command: bash -c 'source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/drivers.launch.py drivers:=v2x_ros_driver'

  torc_pinpoint_driver:
    image: ${DOCKER_ORG}/carma-torc-pinpoint-driver:${DOCKER_TAG}
    container_name: carma-torc-pinpoint-driver
    network_mode: host
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/opt/carma/.ros
    command: bash -c 'source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/drivers.launch.py drivers:=pinpoint_driver'
