# Boolean: A flag indicating whether this plugin shall be activated. If activated, this plugin will publish
#          BSMs when the vehicle's lights and sirens are active.
# Units: N/A
enable_emergency_response_vehicle_plugin : false

# Double: The frequency at which BSMs will be generated and published by this plugin. 
# Units: Hz
bsm_generation_frequency : 10.0

# Double: The distance that the ERV must be from its next route destination point before the point is removed from
#         the list of future route destination points.
# Units: Meters
min_distance_to_next_destination_point : 30.0

# String: The path on the host PC for the CSV file that contains the pre-defined points existing along active emergency vehicle's route.
# Units: N/A
emergency_route_file_path : "DEFAULT_PATH"

# Int: The listening port that this node’s UDP socket will bind to in order to receive data related to the status 
#      of the ERV’s emergency sirens and lights.
listening_port : 1610

# Int: The BSM message ID for the Emergency Response Vehicle. The value will be converted to a 4 element array of uint8_t
#      where each byte of the parameter becomes one element of the array.
bsm_message_id: 8