services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: setup
    volumes:
      - ./carma-messenger:/home/carma/src/carma-messenger:rw
      - ./emergency_response_vehicle_plugin:/home/carma/src/emergency_response_vehicle_plugin:rw
      - ./traffic_incident:/home/carma/src/traffic_incident:rw